// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: device.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClipboardProvider represents the clipboard provider
// Used to identify the clipboard provider
type Clipboard int32

const (
	Clipboard_XClip       Clipboard = 0
	Clipboard_XSel        Clipboard = 1
	Clipboard_WlClipboard Clipboard = 2
	Clipboard_MasOsStd    Clipboard = 4
	Clipboard_WindowsNT10 Clipboard = 5
)

// Enum value maps for Clipboard.
var (
	Clipboard_name = map[int32]string{
		0: "XClip",
		1: "XSel",
		2: "WlClipboard",
		4: "MasOsStd",
		5: "WindowsNT10",
	}
	Clipboard_value = map[string]int32{
		"XClip":       0,
		"XSel":        1,
		"WlClipboard": 2,
		"MasOsStd":    4,
		"WindowsNT10": 5,
	}
)

func (x Clipboard) Enum() *Clipboard {
	p := new(Clipboard)
	*p = x
	return p
}

func (x Clipboard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Clipboard) Descriptor() protoreflect.EnumDescriptor {
	return file_device_proto_enumTypes[0].Descriptor()
}

func (Clipboard) Type() protoreflect.EnumType {
	return &file_device_proto_enumTypes[0]
}

func (x Clipboard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Clipboard.Descriptor instead.
func (Clipboard) EnumDescriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

// Device represents the device information
type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Arch              string    `protobuf:"bytes,2,opt,name=Arch,proto3" json:"Arch,omitempty"`
	UniqueID          string    `protobuf:"bytes,3,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	ClipboardProvider Clipboard `protobuf:"varint,4,opt,name=ClipboardProvider,proto3,enum=belphegor.Clipboard" json:"ClipboardProvider,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Device) GetUniqueID() string {
	if x != nil {
		return x.UniqueID
	}
	return ""
}

func (x *Device) GetClipboardProvider() Clipboard {
	if x != nil {
		return x.ClipboardProvider
	}
	return Clipboard_XClip
}

var File_device_proto protoreflect.FileDescriptor

var file_device_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x62, 0x65, 0x6c, 0x70, 0x68, 0x65, 0x67, 0x6f, 0x72, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x63, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x12, 0x42, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x70,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x65, 0x6c, 0x70, 0x68, 0x65, 0x67, 0x6f, 0x72, 0x2e,
	0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x11, 0x43, 0x6c, 0x69, 0x70, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2a, 0x50, 0x0a, 0x09,
	0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x58, 0x43, 0x6c,
	0x69, 0x70, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x53, 0x65, 0x6c, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x57, 0x6c, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x4d, 0x61, 0x73, 0x4f, 0x73, 0x53, 0x74, 0x64, 0x10, 0x04, 0x12, 0x0f, 0x0a,
	0x0b, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x4e, 0x54, 0x31, 0x30, 0x10, 0x05, 0x42, 0x10,
	0x5a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData = file_device_proto_rawDesc
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_proto_rawDescData)
	})
	return file_device_proto_rawDescData
}

var file_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_device_proto_goTypes = []interface{}{
	(Clipboard)(0), // 0: belphegor.Clipboard
	(*Device)(nil), // 1: belphegor.Device
}
var file_device_proto_depIdxs = []int32{
	0, // 0: belphegor.Device.ClipboardProvider:type_name -> belphegor.Clipboard
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		EnumInfos:         file_device_proto_enumTypes,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_rawDesc = nil
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
