// Code generated by wlgen. DO NOT EDIT.

package wlr

import (
	wl "deedles.dev/wl/client"
	"deedles.dev/wl/wire"
	"fmt"
	"os"
)

const (
	ExtDataControlManagerV1Interface = "ext_data_control_manager_v1"
	ExtDataControlManagerV1Version   = 1
)

// This interface is a manager that allows creating per-seat data device
// controls.
type ExtDataControlManagerV1 struct {

	// OnDelete is called when the object is removed from the tracking
	// system.
	OnDelete func()

	state wire.State
	id    uint32
}

// NewExtDataControlManagerV1 returns a newly instantiated ExtDataControlManagerV1. It is
// primarily intended for use by generated code.
func NewExtDataControlManagerV1(state wire.State) *ExtDataControlManagerV1 {
	return &ExtDataControlManagerV1{state: state}
}

func BindExtDataControlManagerV1(state wire.State, registry wire.Binder, name, version uint32) *ExtDataControlManagerV1 {
	obj := NewExtDataControlManagerV1(state)
	state.Add(obj)
	registry.Bind(name, wire.NewID{Interface: ExtDataControlManagerV1Interface, Version: version, ID: obj.ID()})
	return obj
}

func (obj *ExtDataControlManagerV1) State() wire.State {
	return obj.state
}

func (obj *ExtDataControlManagerV1) Dispatch(msg *wire.MessageBuffer) error {

	return wire.UnknownOpError{
		Interface: "ext_data_control_manager_v1",
		Type:      "event",
		Op:        msg.Op(),
	}
}

func (obj *ExtDataControlManagerV1) ID() uint32 {
	return obj.id
}

func (obj *ExtDataControlManagerV1) SetID(id uint32) {
	obj.id = id
}

func (obj *ExtDataControlManagerV1) Delete() {
	if obj.OnDelete != nil {
		obj.OnDelete()
	}
}

func (obj *ExtDataControlManagerV1) String() string {
	return fmt.Sprintf("%v(%v)", "ext_data_control_manager_v1", obj.id)
}

func (obj *ExtDataControlManagerV1) MethodName(op uint16) string {
	switch op {
	}

	return "unknown method"
}

func (obj *ExtDataControlManagerV1) Interface() string {
	return ExtDataControlManagerV1Interface
}

func (obj *ExtDataControlManagerV1) Version() uint32 {
	return ExtDataControlManagerV1Version
}

// Create a new data source.
func (obj *ExtDataControlManagerV1) CreateDataSource() (id *ExtDataControlSourceV1) {
	builder := wire.NewMessage(obj, 0)

	id = NewExtDataControlSourceV1(obj.state)
	obj.state.Add(id)
	builder.WriteObject(id)

	builder.Method = "create_data_source"
	builder.Args = []any{id}
	obj.state.Enqueue(builder)
	return id
}

// Create a data device that can be used to manage a seat's selection.
func (obj *ExtDataControlManagerV1) GetDataDevice(seat *wl.Seat) (id *ExtDataControlDeviceV1) {
	builder := wire.NewMessage(obj, 1)

	id = NewExtDataControlDeviceV1(obj.state)
	obj.state.Add(id)
	builder.WriteObject(id)
	builder.WriteObject(seat)

	builder.Method = "get_data_device"
	builder.Args = []any{id, seat}
	obj.state.Enqueue(builder)
	return id
}

// All objects created by the manager will still remain valid, until their
// appropriate destroy request has been called.
func (obj *ExtDataControlManagerV1) Destroy() {
	builder := wire.NewMessage(obj, 2)

	builder.Method = "destroy"
	builder.Args = []any{}
	obj.state.Enqueue(builder)
	return
}

const (
	ExtDataControlDeviceV1Interface = "ext_data_control_device_v1"
	ExtDataControlDeviceV1Version   = 1
)

// ExtDataControlDeviceV1Listener is a type that can respond to incoming
// messages for a ExtDataControlDeviceV1 object.
type ExtDataControlDeviceV1Listener interface {
	// The data_offer event introduces a new ext_data_control_offer object,
	// which will subsequently be used in either the
	// ext_data_control_device.selection event (for the regular clipboard
	// selections) or the ext_data_control_device.primary_selection event (for
	// the primary clipboard selections). Immediately following the
	// ext_data_control_device.data_offer event, the new data_offer object
	// will send out ext_data_control_offer.offer events to describe the MIME
	// types it offers.
	DataOffer(id *ExtDataControlOfferV1)

	// The selection event is sent out to notify the client of a new
	// ext_data_control_offer for the selection for this device. The
	// ext_data_control_device.data_offer and the ext_data_control_offer.offer
	// events are sent out immediately before this event to introduce the data
	// offer object. The selection event is sent to a client when a new
	// selection is set. The ext_data_control_offer is valid until a new
	// ext_data_control_offer or NULL is received. The client must destroy the
	// previous selection ext_data_control_offer, if any, upon receiving this
	// event. Regardless, the previous selection will be ignored once a new
	// selection ext_data_control_offer is received.
	//
	// The first selection event is sent upon binding the
	// ext_data_control_device object.
	Selection(id *ExtDataControlOfferV1)

	// This data control object is no longer valid and should be destroyed by
	// the client.
	Finished()

	// The primary_selection event is sent out to notify the client of a new
	// ext_data_control_offer for the primary selection for this device. The
	// ext_data_control_device.data_offer and the ext_data_control_offer.offer
	// events are sent out immediately before this event to introduce the data
	// offer object. The primary_selection event is sent to a client when a
	// new primary selection is set. The ext_data_control_offer is valid until
	// a new ext_data_control_offer or NULL is received. The client must
	// destroy the previous primary selection ext_data_control_offer, if any,
	// upon receiving this event. Regardless, the previous primary selection
	// will be ignored once a new primary selection ext_data_control_offer is
	// received.
	//
	// If the compositor supports primary selection, the first
	// primary_selection event is sent upon binding the
	// ext_data_control_device object.
	PrimarySelection(id *ExtDataControlOfferV1)
}

// This interface allows a client to manage a seat's selection.
//
// When the seat is destroyed, this object becomes inert.
type ExtDataControlDeviceV1 struct {
	// Listener's methods are called by incoming messages from the
	// remote end via Dispatch. If it is nil, messages are silently
	// ignored.
	Listener ExtDataControlDeviceV1Listener

	// OnDelete is called when the object is removed from the tracking
	// system.
	OnDelete func()

	state wire.State
	id    uint32
}

// NewExtDataControlDeviceV1 returns a newly instantiated ExtDataControlDeviceV1. It is
// primarily intended for use by generated code.
func NewExtDataControlDeviceV1(state wire.State) *ExtDataControlDeviceV1 {
	return &ExtDataControlDeviceV1{state: state}
}

func (obj *ExtDataControlDeviceV1) State() wire.State {
	return obj.state
}

func (obj *ExtDataControlDeviceV1) Dispatch(msg *wire.MessageBuffer) error {
	switch msg.Op() {
	case 0:

		id := NewExtDataControlOfferV1(obj.state)
		id.SetID(msg.ReadUint())

		obj.state.Add(id)

		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.DataOffer(
			id,
		)
		return nil

	case 1:

		id, ok := obj.state.Get(msg.ReadUint()).(*ExtDataControlOfferV1)
		if !ok {
			return nil
		}

		obj.state.Add(id)

		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Selection(
			id,
		)
		return nil

	case 2:
		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Finished()
		return nil

	case 3:

		id, ok := obj.state.Get(msg.ReadUint()).(*ExtDataControlOfferV1)
		if !ok {
			return nil
		}

		obj.state.Add(id)

		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.PrimarySelection(
			id,
		)
		return nil
	}

	return wire.UnknownOpError{
		Interface: "ext_data_control_device_v1",
		Type:      "event",
		Op:        msg.Op(),
	}
}

func (obj *ExtDataControlDeviceV1) ID() uint32 {
	return obj.id
}

func (obj *ExtDataControlDeviceV1) SetID(id uint32) {
	obj.id = id
}

func (obj *ExtDataControlDeviceV1) Delete() {
	if obj.OnDelete != nil {
		obj.OnDelete()
	}
}

func (obj *ExtDataControlDeviceV1) String() string {
	return fmt.Sprintf("%v(%v)", "ext_data_control_device_v1", obj.id)
}

func (obj *ExtDataControlDeviceV1) MethodName(op uint16) string {
	switch op {
	case 0:
		return "data_offer"

	case 1:
		return "selection"

	case 2:
		return "finished"

	case 3:
		return "primary_selection"
	}

	return "unknown method"
}

func (obj *ExtDataControlDeviceV1) Interface() string {
	return ExtDataControlDeviceV1Interface
}

func (obj *ExtDataControlDeviceV1) Version() uint32 {
	return ExtDataControlDeviceV1Version
}

// This request asks the compositor to set the selection to the data from
// the source on behalf of the client.
//
// The given source may not be used in any further set_selection or
// set_primary_selection requests. Attempting to use a previously used
// source triggers the used_source protocol error.
//
// To unset the selection, set the source to NULL.
func (obj *ExtDataControlDeviceV1) SetSelection(source *ExtDataControlSourceV1) {
	builder := wire.NewMessage(obj, 0)

	builder.WriteObject(source)

	builder.Method = "set_selection"
	builder.Args = []any{source}
	obj.state.Enqueue(builder)
	return
}

// Destroys the data device object.
func (obj *ExtDataControlDeviceV1) Destroy() {
	builder := wire.NewMessage(obj, 1)

	builder.Method = "destroy"
	builder.Args = []any{}
	obj.state.Enqueue(builder)
	return
}

// This request asks the compositor to set the primary selection to the
// data from the source on behalf of the client.
//
// The given source may not be used in any further set_selection or
// set_primary_selection requests. Attempting to use a previously used
// source triggers the used_source protocol error.
//
// To unset the primary selection, set the source to NULL.
//
// The compositor will ignore this request if it does not support primary
// selection.
func (obj *ExtDataControlDeviceV1) SetPrimarySelection(source *ExtDataControlSourceV1) {
	builder := wire.NewMessage(obj, 2)

	builder.WriteObject(source)

	builder.Method = "set_primary_selection"
	builder.Args = []any{source}
	obj.state.Enqueue(builder)
	return
}

type ExtDataControlDeviceV1Error int64

const (
	// source given to set_selection or set_primary_selection was already used before
	ExtDataControlDeviceV1ErrorUsedSource ExtDataControlDeviceV1Error = 1
)

func (enum ExtDataControlDeviceV1Error) String() string {
	switch enum {
	case 1:
		return "ExtDataControlDeviceV1ErrorUsedSource"
	}

	return "<invalid ExtDataControlDeviceV1Error>"
}

const (
	ExtDataControlSourceV1Interface = "ext_data_control_source_v1"
	ExtDataControlSourceV1Version   = 1
)

// ExtDataControlSourceV1Listener is a type that can respond to incoming
// messages for a ExtDataControlSourceV1 object.
type ExtDataControlSourceV1Listener interface {
	// Request for data from the client. Send the data as the specified MIME
	// type over the passed file descriptor, then close it.
	Send(mimeType string, fd *os.File)

	// This data source is no longer valid. The data source has been replaced
	// by another data source.
	//
	// The client should clean up and destroy this data source.
	Cancelled()
}

// The ext_data_control_source object is the source side of a
// ext_data_control_offer. It is created by the source client in a data
// transfer and provides a way to describe the offered data and a way to
// respond to requests to transfer the data.
type ExtDataControlSourceV1 struct {
	// Listener's methods are called by incoming messages from the
	// remote end via Dispatch. If it is nil, messages are silently
	// ignored.
	Listener ExtDataControlSourceV1Listener

	// OnDelete is called when the object is removed from the tracking
	// system.
	OnDelete func()

	state wire.State
	id    uint32
}

// NewExtDataControlSourceV1 returns a newly instantiated ExtDataControlSourceV1. It is
// primarily intended for use by generated code.
func NewExtDataControlSourceV1(state wire.State) *ExtDataControlSourceV1 {
	return &ExtDataControlSourceV1{state: state}
}

func (obj *ExtDataControlSourceV1) State() wire.State {
	return obj.state
}

func (obj *ExtDataControlSourceV1) Dispatch(msg *wire.MessageBuffer) error {
	switch msg.Op() {
	case 0:

		mimeType := msg.ReadString()

		fd := msg.ReadFile()

		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Send(
			mimeType,
			fd,
		)
		return nil

	case 1:
		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Cancelled()
		return nil
	}

	return wire.UnknownOpError{
		Interface: "ext_data_control_source_v1",
		Type:      "event",
		Op:        msg.Op(),
	}
}

func (obj *ExtDataControlSourceV1) ID() uint32 {
	return obj.id
}

func (obj *ExtDataControlSourceV1) SetID(id uint32) {
	obj.id = id
}

func (obj *ExtDataControlSourceV1) Delete() {
	if obj.OnDelete != nil {
		obj.OnDelete()
	}
}

func (obj *ExtDataControlSourceV1) String() string {
	return fmt.Sprintf("%v(%v)", "ext_data_control_source_v1", obj.id)
}

func (obj *ExtDataControlSourceV1) MethodName(op uint16) string {
	switch op {
	case 0:
		return "send"

	case 1:
		return "cancelled"
	}

	return "unknown method"
}

func (obj *ExtDataControlSourceV1) Interface() string {
	return ExtDataControlSourceV1Interface
}

func (obj *ExtDataControlSourceV1) Version() uint32 {
	return ExtDataControlSourceV1Version
}

// This request adds a MIME type to the set of MIME types advertised to
// targets. Can be called several times to offer multiple types.
//
// Calling this after ext_data_control_device.set_selection is a protocol
// error.
func (obj *ExtDataControlSourceV1) Offer(mimeType string) {
	builder := wire.NewMessage(obj, 0)

	builder.WriteString(mimeType)

	builder.Method = "offer"
	builder.Args = []any{mimeType}
	obj.state.Enqueue(builder)
	return
}

// Destroys the data source object.
func (obj *ExtDataControlSourceV1) Destroy() {
	builder := wire.NewMessage(obj, 1)

	builder.Method = "destroy"
	builder.Args = []any{}
	obj.state.Enqueue(builder)
	return
}

type ExtDataControlSourceV1Error int64

const (
	// offer sent after ext_data_control_device.set_selection
	ExtDataControlSourceV1ErrorInvalidOffer ExtDataControlSourceV1Error = 1
)

func (enum ExtDataControlSourceV1Error) String() string {
	switch enum {
	case 1:
		return "ExtDataControlSourceV1ErrorInvalidOffer"
	}

	return "<invalid ExtDataControlSourceV1Error>"
}

const (
	ExtDataControlOfferV1Interface = "ext_data_control_offer_v1"
	ExtDataControlOfferV1Version   = 1
)

// ExtDataControlOfferV1Listener is a type that can respond to incoming
// messages for a ExtDataControlOfferV1 object.
type ExtDataControlOfferV1Listener interface {
	// Sent immediately after creating the ext_data_control_offer object.
	// One event per offered MIME type.
	Offer(mimeType string)
}

// A ext_data_control_offer represents a piece of data offered for transfer
// by another client (the source client). The offer describes the different
// MIME types that the data can be converted to and provides the mechanism
// for transferring the data directly from the source client.
type ExtDataControlOfferV1 struct {
	// Listener's methods are called by incoming messages from the
	// remote end via Dispatch. If it is nil, messages are silently
	// ignored.
	Listener ExtDataControlOfferV1Listener

	// OnDelete is called when the object is removed from the tracking
	// system.
	OnDelete func()

	state wire.State
	id    uint32
}

// NewExtDataControlOfferV1 returns a newly instantiated ExtDataControlOfferV1. It is
// primarily intended for use by generated code.
func NewExtDataControlOfferV1(state wire.State) *ExtDataControlOfferV1 {
	return &ExtDataControlOfferV1{state: state}
}

func (obj *ExtDataControlOfferV1) State() wire.State {
	return obj.state
}

func (obj *ExtDataControlOfferV1) Dispatch(msg *wire.MessageBuffer) error {
	switch msg.Op() {
	case 0:

		mimeType := msg.ReadString()

		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Offer(
			mimeType,
		)
		return nil
	}

	return wire.UnknownOpError{
		Interface: "ext_data_control_offer_v1",
		Type:      "event",
		Op:        msg.Op(),
	}
}

func (obj *ExtDataControlOfferV1) ID() uint32 {
	return obj.id
}

func (obj *ExtDataControlOfferV1) SetID(id uint32) {
	obj.id = id
}

func (obj *ExtDataControlOfferV1) Delete() {
	if obj.OnDelete != nil {
		obj.OnDelete()
	}
}

func (obj *ExtDataControlOfferV1) String() string {
	return fmt.Sprintf("%v(%v)", "ext_data_control_offer_v1", obj.id)
}

func (obj *ExtDataControlOfferV1) MethodName(op uint16) string {
	switch op {
	case 0:
		return "offer"
	}

	return "unknown method"
}

func (obj *ExtDataControlOfferV1) Interface() string {
	return ExtDataControlOfferV1Interface
}

func (obj *ExtDataControlOfferV1) Version() uint32 {
	return ExtDataControlOfferV1Version
}

// To transfer the offered data, the client issues this request and
// indicates the MIME type it wants to receive. The transfer happens
// through the passed file descriptor (typically created with the pipe
// system call). The source client writes the data in the MIME type
// representation requested and then closes the file descriptor.
//
// The receiving client reads from the read end of the pipe until EOF and
// then closes its end, at which point the transfer is complete.
//
// This request may happen multiple times for different MIME types.
func (obj *ExtDataControlOfferV1) Receive(mimeType string, fd *os.File) {
	builder := wire.NewMessage(obj, 0)

	builder.WriteString(mimeType)
	builder.WriteFile(fd)

	builder.Method = "receive"
	builder.Args = []any{mimeType, fd}
	obj.state.Enqueue(builder)
	return
}

// Destroys the data offer object.
func (obj *ExtDataControlOfferV1) Destroy() {
	builder := wire.NewMessage(obj, 1)

	builder.Method = "destroy"
	builder.Args = []any{}
	obj.state.Enqueue(builder)
	return
}
