version: 2
project_name: belphegor
before:
  hooks:
    - go generate ./...

builds:
  - id: default
    main: "./cmd/cli/"
    binary: belphegor
    mod_timestamp: '{{ .CommitTimestamp }}'
    ignore:
      - goos: windows
        goarch: arm
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
      - osusergo
      - nodbus
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'
      - -X {{ .ModulePath }}/internal/metadata.Version={{ .Version }}
      - -X {{ .ModulePath }}/internal/metadata.CommitHash={{ .Commit }}
      - -X {{ .ModulePath }}/internal/metadata.BuildTime={{ .CommitDate }}

  - id: wl_clipboard
    main: "./cmd/cli/"
    binary: belphegor
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
      - osusergo
      - nodbus
      - wl_clipboard
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'
      - -X {{ .ModulePath }}/internal/metadata.Version={{ .Version }}
      - -X {{ .ModulePath }}/internal/metadata.CommitHash={{ .Commit }}
      - -X {{ .ModulePath }}/internal/metadata.BuildTime={{ .CommitDate }}

archives:
  - id: default
    ids:
      - default
    formats: [ binary ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: wl_clipboard
    ids:
      - wl_clipboard
    formats: [ binary ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_wl_clipboard"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: 'v{{ .Version }}'
  make_latest: true

nfpms:
  - &base
    id: default
    package_name: belphegor
    ids:
      - default
    vendor: labi-le
    homepage: https://github.com/labi-le/belphegor
    maintainer: labi-le <i@labile.cc>
    description: "Share clipboard on network (Native Wayland)"
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux

  - <<: *base
    id: wl_clipboard
    package_name: belphegor_wl-clipboard
    ids:
      - wl_clipboard
    description: "Share clipboard on network (via wl-clipboard utility)"

    recommends: [ ]
    dependencies:
      - wl-clipboard

    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_wl_clipboard"