version: 2
project_name: belphegor
before:
  hooks:
    - go generate ./...

builds:
  - &build_defaults
    id: default
    main: "./cmd/cli/"
    binary: belphegor
    mod_timestamp: '{{ .CommitTimestamp }}'
    ignore:
      - goos: windows
        goarch: arm
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
      - osusergo
      - nodbus
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'
      - -X {{ .ModulePath }}/internal/metadata.Version={{ .Version }}
      - -X {{ .ModulePath }}/internal/metadata.CommitHash={{ .Commit }}
      - -X {{ .ModulePath }}/internal/metadata.BuildTime={{ .CommitDate }}

  - <<: *build_defaults
    id: wl_clipboard
    goos:
      - linux
    tags:
      - netgo
      - osusergo
      - nodbus
      - wl_clipboard

  - <<: *build_defaults
    id: x11
    goos:
      - linux
    tags:
      - netgo
      - osusergo
      - nodbus
      - x11

archives:
  - id: default
    ids:
      - default
    formats: [ binary ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: wl_clipboard
    ids:
      - wl_clipboard
    formats: [ binary ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_wl_clipboard"

  - id: x11
    ids:
      - x11
    formats: [ binary ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_x11"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: 'v{{ .Version }}'
  make_latest: true

nfpms:
  - &nfpm_defaults
    id: default
    package_name: belphegor
    ids:
      - default
    vendor: labi-le
    homepage: https://github.com/labi-le/belphegor
    maintainer: labi-le <i@labile.cc>
    description: "Share clipboard on network (Wayland: ext_data_control_v1)"
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux

  - <<: *nfpm_defaults
    id: wl_clipboard
    package_name: belphegor-wl-clipboard
    ids:
      - wl_clipboard
    description: "Share clipboard on network (via wl-clipboard utility)"
    recommends: [ ]
    dependencies:
      - wl-clipboard
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_wl_clipboard"

  - <<: *nfpm_defaults
    id: x11
    package_name: belphegor-x11
    ids:
      - x11
    description: "Share clipboard on network (X11: XFixes)"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_x11"