version: 2
project_name: belphegor
before:
  hooks:
    - go generate ./...
archives:
  - format: binary
builds:
  - main: "./cmd/cli/"
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
    tags:
      - netgo
      - osusergo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'
      - -X {{ .ModulePath }}/internal.Version={{ .Version }}
      - -X {{ .ModulePath }}/internal.CommitHash={{ .Commit }}
      - -X {{ .ModulePath }}/internal.BuildTime={{ .CommitDate }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: 'v{{ .Version }}'
  make_latest: true

nfpms:
  - vendor: labi-le
    homepage: https://github.com/labi-le/belphegor
    maintainer: labi-le <i@labile.cc>
    description: |-
      share clipboard on network

    license: MIT

    formats:
      - deb
      - rpm
      - archlinux

    recommends:
      - wl-clipboard
      - xclip
      - xsel

    version_metadata: git