// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: encrypted.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_encrypted_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_encrypted_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_encrypted_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_encrypted_proto protoreflect.FileDescriptor

const file_encrypted_proto_rawDesc = "" +
	"\n" +
	"\x0fencrypted.proto\x12\tbelphegor\",\n" +
	"\x10EncryptedMessage\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\fR\aMessageB\x16Z\x14internal/types/protob\x06proto3"

var (
	file_encrypted_proto_rawDescOnce sync.Once
	file_encrypted_proto_rawDescData []byte
)

func file_encrypted_proto_rawDescGZIP() []byte {
	file_encrypted_proto_rawDescOnce.Do(func() {
		file_encrypted_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encrypted_proto_rawDesc), len(file_encrypted_proto_rawDesc)))
	})
	return file_encrypted_proto_rawDescData
}

var file_encrypted_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_encrypted_proto_goTypes = []any{
	(*EncryptedMessage)(nil), // 0: belphegor.EncryptedMessage
}
var file_encrypted_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encrypted_proto_init() }
func file_encrypted_proto_init() {
	if File_encrypted_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encrypted_proto_rawDesc), len(file_encrypted_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encrypted_proto_goTypes,
		DependencyIndexes: file_encrypted_proto_depIdxs,
		MessageInfos:      file_encrypted_proto_msgTypes,
	}.Build()
	File_encrypted_proto = out.File
	file_encrypted_proto_goTypes = nil
	file_encrypted_proto_depIdxs = nil
}
