// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: event.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_HEARTBEAT Type = 0
	Type_UPDATE    Type = 1
	Type_HANDSHAKE Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "HEARTBEAT",
		1: "UPDATE",
		2: "HANDSHAKE",
	}
	Type_value = map[string]int32{
		"HEARTBEAT": 0,
		"UPDATE":    1,
		"HANDSHAKE": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Created *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Created,proto3" json:"Created,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Heartbeat
	//	*Event_Message
	//	*Event_Handshake
	Payload       isEvent_Payload `protobuf_oneof:"Payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetHeartbeat() *HeartbeatPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Event) GetMessage() *EncryptedMessage {
	if x != nil {
		if x, ok := x.Payload.(*Event_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Event) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Event_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Heartbeat struct {
	Heartbeat *HeartbeatPayload `protobuf:"bytes,2,opt,name=Heartbeat,proto3,oneof"`
}

type Event_Message struct {
	Message *EncryptedMessage `protobuf:"bytes,3,opt,name=Message,proto3,oneof"`
}

type Event_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,4,opt,name=Handshake,proto3,oneof"`
}

func (*Event_Heartbeat) isEvent_Payload() {}

func (*Event_Message) isEvent_Payload() {}

func (*Event_Handshake) isEvent_Payload() {}

type HeartbeatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPayload) Reset() {
	*x = HeartbeatPayload{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPayload) ProtoMessage() {}

func (x *HeartbeatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPayload.ProtoReflect.Descriptor instead.
func (*HeartbeatPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\tbelphegor\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fhandshake.proto\x1a\rmessage.proto\"\xf4\x01\n" +
	"\x05Event\x124\n" +
	"\aCreated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\aCreated\x12;\n" +
	"\tHeartbeat\x18\x02 \x01(\v2\x1b.belphegor.HeartbeatPayloadH\x00R\tHeartbeat\x127\n" +
	"\aMessage\x18\x03 \x01(\v2\x1b.belphegor.EncryptedMessageH\x00R\aMessage\x124\n" +
	"\tHandshake\x18\x04 \x01(\v2\x14.belphegor.HandshakeH\x00R\tHandshakeB\t\n" +
	"\aPayload\"\x12\n" +
	"\x10HeartbeatPayload*0\n" +
	"\x04Type\x12\r\n" +
	"\tHEARTBEAT\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\r\n" +
	"\tHANDSHAKE\x10\x02B\x16Z\x14internal/types/protob\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_proto_goTypes = []any{
	(Type)(0),                     // 0: belphegor.Type
	(*Event)(nil),                 // 1: belphegor.Event
	(*HeartbeatPayload)(nil),      // 2: belphegor.HeartbeatPayload
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*EncryptedMessage)(nil),      // 4: belphegor.EncryptedMessage
	(*Handshake)(nil),             // 5: belphegor.Handshake
}
var file_event_proto_depIdxs = []int32{
	3, // 0: belphegor.Event.Created:type_name -> google.protobuf.Timestamp
	2, // 1: belphegor.Event.Heartbeat:type_name -> belphegor.HeartbeatPayload
	4, // 2: belphegor.Event.Message:type_name -> belphegor.EncryptedMessage
	5, // 3: belphegor.Event.Handshake:type_name -> belphegor.Handshake
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_handshake_proto_init()
	file_message_proto_init()
	file_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Heartbeat)(nil),
		(*Event_Message)(nil),
		(*Event_Handshake)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
