// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: greetmessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GreetMessage represents the greeting message
// Used to shake hands with other nodes
type GreetMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string  `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Device    *Device `protobuf:"bytes,3,opt,name=Device,proto3" json:"Device,omitempty"`
	Port      uint32  `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty"`
	PublicKey []byte  `protobuf:"bytes,6,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
}

func (x *GreetMessage) Reset() {
	*x = GreetMessage{}
	mi := &file_greetmessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetMessage) ProtoMessage() {}

func (x *GreetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_greetmessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetMessage.ProtoReflect.Descriptor instead.
func (*GreetMessage) Descriptor() ([]byte, []int) {
	return file_greetmessage_proto_rawDescGZIP(), []int{0}
}

func (x *GreetMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GreetMessage) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *GreetMessage) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GreetMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_greetmessage_proto protoreflect.FileDescriptor

var file_greetmessage_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x65, 0x65, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x65, 0x6c, 0x70, 0x68, 0x65, 0x67, 0x6f, 0x72, 0x1a,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01,
	0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x65, 0x6c, 0x70, 0x68,
	0x65, 0x67, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x16, 0x5a, 0x14, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greetmessage_proto_rawDescOnce sync.Once
	file_greetmessage_proto_rawDescData = file_greetmessage_proto_rawDesc
)

func file_greetmessage_proto_rawDescGZIP() []byte {
	file_greetmessage_proto_rawDescOnce.Do(func() {
		file_greetmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_greetmessage_proto_rawDescData)
	})
	return file_greetmessage_proto_rawDescData
}

var file_greetmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_greetmessage_proto_goTypes = []any{
	(*GreetMessage)(nil), // 0: belphegor.GreetMessage
	(*Device)(nil),       // 1: belphegor.Device
}
var file_greetmessage_proto_depIdxs = []int32{
	1, // 0: belphegor.GreetMessage.Device:type_name -> belphegor.Device
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_greetmessage_proto_init() }
func file_greetmessage_proto_init() {
	if File_greetmessage_proto != nil {
		return
	}
	file_device_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greetmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_greetmessage_proto_goTypes,
		DependencyIndexes: file_greetmessage_proto_depIdxs,
		MessageInfos:      file_greetmessage_proto_msgTypes,
	}.Build()
	File_greetmessage_proto = out.File
	file_greetmessage_proto_rawDesc = nil
	file_greetmessage_proto_goTypes = nil
	file_greetmessage_proto_depIdxs = nil
}
