// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: header.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mime int32

const (
	Mime_TEXT  Mime = 0
	Mime_IMAGE Mime = 1
)

// Enum value maps for Mime.
var (
	Mime_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
	}
	Mime_value = map[string]int32{
		"TEXT":  0,
		"IMAGE": 1,
	}
)

func (x Mime) Enum() *Mime {
	p := new(Mime)
	*p = x
	return p
}

func (x Mime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mime) Descriptor() protoreflect.EnumDescriptor {
	return file_header_proto_enumTypes[0].Descriptor()
}

func (Mime) Type() protoreflect.EnumType {
	return &file_header_proto_enumTypes[0]
}

func (x Mime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mime.Descriptor instead.
func (Mime) EnumDescriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{0}
}

// ClipboardProvider represents the clipboard provider
// Used to identify the clipboard provider
type Clipboard int32

const (
	Clipboard_XClip       Clipboard = 0
	Clipboard_XSel        Clipboard = 1
	Clipboard_WlClipboard Clipboard = 2
	Clipboard_MasOsStd    Clipboard = 4
	Clipboard_WindowsNT10 Clipboard = 5
	Clipboard_Null        Clipboard = 6
)

// Enum value maps for Clipboard.
var (
	Clipboard_name = map[int32]string{
		0: "XClip",
		1: "XSel",
		2: "WlClipboard",
		4: "MasOsStd",
		5: "WindowsNT10",
		6: "Null",
	}
	Clipboard_value = map[string]int32{
		"XClip":       0,
		"XSel":        1,
		"WlClipboard": 2,
		"MasOsStd":    4,
		"WindowsNT10": 5,
		"Null":        6,
	}
)

func (x Clipboard) Enum() *Clipboard {
	p := new(Clipboard)
	*p = x
	return p
}

func (x Clipboard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Clipboard) Descriptor() protoreflect.EnumDescriptor {
	return file_header_proto_enumTypes[1].Descriptor()
}

func (Clipboard) Type() protoreflect.EnumType {
	return &file_header_proto_enumTypes[1]
}

func (x Clipboard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Clipboard.Descriptor instead.
func (Clipboard) EnumDescriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{1}
}

// Header represents the header of a message
type Header struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	From              int64                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	MimeType          Mime                   `protobuf:"varint,2,opt,name=MimeType,proto3,enum=belphegor.Mime" json:"MimeType,omitempty"`
	ID                int64                  `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	Created           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Created,proto3" json:"Created,omitempty"`
	ClipboardProvider Clipboard              `protobuf:"varint,5,opt,name=ClipboardProvider,proto3,enum=belphegor.Clipboard" json:"ClipboardProvider,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Header) GetMimeType() Mime {
	if x != nil {
		return x.MimeType
	}
	return Mime_TEXT
}

func (x *Header) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Header) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Header) GetClipboardProvider() Clipboard {
	if x != nil {
		return x.ClipboardProvider
	}
	return Clipboard_XClip
}

var File_header_proto protoreflect.FileDescriptor

const file_header_proto_rawDesc = "" +
	"\n" +
	"\fheader.proto\x12\tbelphegor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x06Header\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x03R\x04From\x12+\n" +
	"\bMimeType\x18\x02 \x01(\x0e2\x0f.belphegor.MimeR\bMimeType\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\x03R\x02ID\x124\n" +
	"\aCreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aCreated\x12B\n" +
	"\x11ClipboardProvider\x18\x05 \x01(\x0e2\x14.belphegor.ClipboardR\x11ClipboardProvider*\x1b\n" +
	"\x04Mime\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01*Z\n" +
	"\tClipboard\x12\t\n" +
	"\x05XClip\x10\x00\x12\b\n" +
	"\x04XSel\x10\x01\x12\x0f\n" +
	"\vWlClipboard\x10\x02\x12\f\n" +
	"\bMasOsStd\x10\x04\x12\x0f\n" +
	"\vWindowsNT10\x10\x05\x12\b\n" +
	"\x04Null\x10\x06B\x16Z\x14internal/types/protob\x06proto3"

var (
	file_header_proto_rawDescOnce sync.Once
	file_header_proto_rawDescData []byte
)

func file_header_proto_rawDescGZIP() []byte {
	file_header_proto_rawDescOnce.Do(func() {
		file_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_header_proto_rawDesc), len(file_header_proto_rawDesc)))
	})
	return file_header_proto_rawDescData
}

var file_header_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_header_proto_goTypes = []any{
	(Mime)(0),                     // 0: belphegor.Mime
	(Clipboard)(0),                // 1: belphegor.Clipboard
	(*Header)(nil),                // 2: belphegor.Header
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_header_proto_depIdxs = []int32{
	0, // 0: belphegor.Header.MimeType:type_name -> belphegor.Mime
	3, // 1: belphegor.Header.Created:type_name -> google.protobuf.Timestamp
	1, // 2: belphegor.Header.ClipboardProvider:type_name -> belphegor.Clipboard
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_header_proto_init() }
func file_header_proto_init() {
	if File_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_header_proto_rawDesc), len(file_header_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_header_proto_goTypes,
		DependencyIndexes: file_header_proto_depIdxs,
		EnumInfos:         file_header_proto_enumTypes,
		MessageInfos:      file_header_proto_msgTypes,
	}.Build()
	File_header_proto = out.File
	file_header_proto_goTypes = nil
	file_header_proto_depIdxs = nil
}
