name: Update flake.nix on Release

permissions:
  contents: write
  pull-requests: write

on:
  push:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Update flake.nix
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get latest release version
          release=$(curl -sL "https://api.github.com/repos/labi-le/belphegor/releases/latest" | jq -r '.tag_name')
          version=${release#v}
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Latest version: $version"
          
          # Get checksums
          curl -sL "https://github.com/labi-le/belphegor/releases/download/$release/checksums.txt" -o checksums.txt
          
          # Get hashes and convert them
          amd64_hash=$(grep "belphegor_${version}_linux_amd64$" checksums.txt | cut -d ' ' -f1)
          arm_hash=$(grep "belphegor_${version}_linux_armv6$" checksums.txt | cut -d ' ' -f1)
          
          amd64_sri=$(nix hash convert --to sri "sha256:$amd64_hash")
          arm_sri=$(nix hash convert --to sri "sha256:$arm_hash")
          
          echo "AMD64_SRI=$amd64_sri" >> $GITHUB_ENV
          echo "ARMV6_SRI=$arm_sri" >> $GITHUB_ENV
          
          echo "AMD64 SRI: $amd64_sri"
          echo "ARM SRI: $arm_sri"
          
          # Create commit message
          echo "COMMIT_MSG=chore: update flake.nix and flake.lock to v$version" >> $GITHUB_ENV
          echo "PR_TITLE=Update flake.nix to v$version" >> $GITHUB_ENV
          
          # Update version
          sed -i "s/version = \"[^\"]*\"/version = \"$version\"/" flake.nix
          
          # Update AMD64 hash
          sed -i "s|hash = \"sha256-[^\"]*\"; # x86_64-linux|hash = \"$amd64_sri\"; # x86_64-linux|" flake.nix
          
          # Update ARM hash
          sed -i "s|hash = \"sha256-[^\"]*\"; # aarch64-linux|hash = \"$arm_sri\"; # aarch64-linux|" flake.nix
          
          # Update flake.lock
          nix flake update
          
          # Remove checksums file
          rm checksums.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${{ env.COMMIT_MSG }}
          title: ${{ env.PR_TITLE }}
          body: |
            Automatic update of flake.nix for release v${{ env.VERSION }}
            
            Updates:
            - Version: ${{ env.VERSION }}
            - x86_64-linux hash: ${{ env.AMD64_SRI }}
            - aarch64-linux hash: ${{ env.ARMV6_SRI }}
            - Updated flake.lock
          branch: update-flake
          delete-branch: true